### ISSUE TITLE
Rails 5 - undefined method `arel_attributes_with_values_for_create'

### ISSUE THREAD

**Issue by calvinchso** [einzige/sneaky-save#21]
Anyone is using this gem with Rails 5? It looks like Rails 5 AR doesn't have "arel_attributes_with_values_for_create" anymore and thus it's broken.

Any suggestion?

```
[2018-08-23 10:08:54.327799 #22071] ERROR: undefined method `arel_attributes_with_values_for_create' for #<Candy:0x00007fd047782fe8>
[2018-08-23 10:08:54.328175 #22071] ERROR: /Users/calvin/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.1/lib/active_model/attribute_methods.rb:430:in `method_missing'
/Users/calvin/.rvm/gems/ruby-2.5.1/gems/sneaky-save-0.1.3/lib/sneaky-save.rb:87:in `sneaky_attributes_values'
/Users/calvin/.rvm/gems/ruby-2.5.1/gems/sneaky-save-0.1.3/lib/sneaky-save.rb:45:in `sneaky_create'
/Users/calvin/.rvm/gems/ruby-2.5.1/gems/sneaky-save-0.1.3/lib/sneaky-save.rb:33:in `sneaky_create_or_update'
/Users/calvin/.rvm/gems/ruby-2.5.1/gems/sneaky-save-0.1.3/lib/sneaky-save.rb:16:in `sneaky_save'
```

**Comment by einzige** [comment]
We'll figure this out soon

**Comment by robklassy** [comment]
Is there a workaround for this?

**Comment by tushar0837** [comment]
any updates here @einzige

**Comment by yossiedri** [comment]
im having the same error Is there a fix for this?
rails 5 ruby 2.6

**Comment by robklassy** [comment]
@yossiedri I don't think there is a fix, I basically had to write the method myself to make it work
